# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='klyppuser',
            name='profile_type',
            field=models.CharField(choices=[('1', 'Stylist'), ('2', 'Client'), ('3', 'Both')], default='1', max_length=7),
        ),
    ]
